# MySQL connection
spring.datasource.url=jdbc:mysql://b3p5m8nhncgiqy1daeus-mysql.services.clever-cloud.com:3306/b3p5m8nhncgiqy1daeus
spring.datasource.username=urowmyrks8sa1rih
spring.datasource.password=RsKRqsn19uGmkebas6WR

server.port=${PORT:8080}
# ------------------------
# JPA / Hibernate
# ------------------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Optional: Better logging for SQL statements
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE